services:
  azure-event-hubs-test-client:
    build: 
      context: .
      target: development
    ports:
      - "3012:3012"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/node/package.json
