environment: production
name: azure-event-hubs-test-client
image: azure-event-hubs-test-client

container:
  cookieSecret: notreallyasecretnotreallyasecret
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3012

ingress: {}

deployment: {}
